In [ ]:
print('Hello, world!')

Hello, world!


#происходит что то странное

* текст форматируется?


In [ ]:

txt = open('text_skillbox.txt')
txt.read()


'Я изучаю Data Science.\n\nДля этого я прохожу курсы и читаю статьи на Skillbox. \n\nЯ молодец и вообще.'

In [ ]:
import pandas as pd
#df = pd.DataFrame()
df = pd.read_csv('IMDB Dataset.csv')


In [ ]:
df.dtypes

review       object
sentiment    object
dtype: object

In [ ]:
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [ ]:
weight =0.1
def neural_network(input, weight):
   prediction = input * weight
   return prediction

In [ ]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input,weight)
print(pred)

0.8500000000000001


In [ ]:
import numpy as np
# игр % побед болельщиков
ih_wgt = np.array([
[0.1, 0.2, -0.1], # hid[0]
[-0.1,0.1, 0.9], # hid[l]
[0.1, 0.4, 0.1]]).T # hid[2]

# hid[0] hid[l] hid[2]
hp_wgt = np.array([
[0.3, 1.1, -0.3], # травмы?
[0.1, 0.2, 0.0], # победа?
[0.0, 1.3, 0.1] ]).T# печаль?
weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
  hid = input.dot(weights[0])
  pred = hid.dot(weights[1])
  return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)


[0.2135 0.145  0.5065]


In [ ]:
knob_weight =0.5
input = 0.5
goal_pred =0.8
pred = input * knob_weight
error = (pred - goal_pred)**2
print(error)


0.30250000000000005


## Горячо - хлолдно

In [ ]:
weight = 0.1
lr = 0.01
def neural_network(input, weight):
  prediction = input * weight
  return prediction

number_of_toes = [8.5]
win_or_lose_binary = [1] # (победа!!!)
input = number_of_toes[0]
true = win_or_lose_binary[0]

pred = neural_network(input, weight)

error = (pred - true) ** 2
print(error)


0.022499999999999975


In [ ]:
lr = 0.01
p_up = neural_network(input,weight+lr)
e_up = (p_up - true) ** 2
print(e_up)


0.004224999999999993


In [ ]:
lг = 0.01
p_dn = neural_network(input,weight -lr)
e_dn = (p_dn - true) ** 2
print(e_dn)


0.05522499999999994
8.5


In [ ]:
weight = 0.5
input = 0.5
goal_prediction = 0.8
step_amount = 0.001
for iteration in range(1101):
  prediction = input * weight
  error = (prediction - goal_prediction) ** 2

  print("Error:" + str(error) + " Prediction:" + str(prediction))

  up_prediction = input * (weight + step_amount) #◄------ Попробовать увеличить!
  up_error = (goal_prediction - up_prediction) ** 2

  down_prediction = input * (weight - step_amount) #◄------ Попробовать уменьшить!
  down_error = (goal_prediction - down_prediction) ** 2

  if(down_error < up_error):
    weight = weight - step_amount #◄-------- , Е(Ли уменьшение дало лучший результат, уменьшить!
  if(down_error > up_error):
    weight = weight + step_amount #◄ i Если увеличение дало лучший результат, увеличить!

##Градиентный спуск

In [ ]:
weight =0.5
goal_pred =0.8
input =2

for iteration in range(20):
  pred = input * weight
  error = (pred - goal_pred) ** 2
  direction_and_amount = (pred - goal_pred) * input
  weight = weight - direction_and_amount
  print("Error:" + str(error) + " Prediction:" + str(pred))

In [ ]:
weight, goal_pred, input = (0.0, 0.8, 2)
for iteration in range(20):
  pred = input * weight #В этих строках кроется секрет
  error = (pred - goal_pred) ** 2 #
  delta = pred - goal_pred
  weight_delta = delta * input
  weight = weight - weight_delta
  print("Error:" + str(error) + " Prediction:" + str(pred))

Добавим альфа для того чтобы избежать расхождения

In [ ]:
weight =0.5
goal_pred =0.8
input = 2
alpha =0.1 #Что случится, если сделать альфа-коэффициент слишком большим или слишком маленьким? А если сделать его отрицательным?
for iteration in range(20):
  pred = input * weight
  error = (pred - goal_pred) ** 2
  derivative = input * (pred - goal_pred)
  weight = weight - (alpha * derivative)
  print("Error:" + str(error) + " Prediction:" + str(pred))

In [ ]:
w = 0.5
inp =2
al = 0.1

goal = 0.8

for i in range(20):
  pred = inp*w
  err = (pred-goal)**2
  delta = pred-goal
  dw = delta*input
  w = w- dw*al
  print("Error:" + str(error) + " Prediction:" + str(pred))

#Читерное решение задачи про диабет, Keras:
1.   Чтение данных
2.   Обучение + проверка



In [ ]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
import pandas as pd

#df = pd.DataFrame()
df = pd.read_csv('diabetes_binary_5050split_health_indicators_BRFSS2015.csv')
# задаем для воспроизводимости результатов
numpy.random.seed(2)

# загружаем датасет, соответствующий последним пяти годам до определение диагноза
#dataset = numpy.loadtxt("diabetes_binary_5050split_health_indicators_BRFSS2015.csv", delimiter=",")
dataset = df.to_numpy()
numpy.random.shuffle(dataset)
#df
#df.dtypes
print(dataset)
print(dataset[:,0])
dataset[:,1:22]
#df.describe()



[[ 1.  1.  0. ...  8.  4.  3.]
 [ 0.  1.  1. ...  7.  6.  2.]
 [ 0.  1.  1. ... 10.  6.  6.]
 ...
 [ 0.  0.  0. ...  3.  5.  3.]
 [ 0.  0.  0. ... 11.  6.  8.]
 [ 1.  1.  1. ... 11.  5.  6.]]
[1. 0. 0. ... 0. 0. 1.]


array([[ 1.,  0.,  1., ...,  8.,  4.,  3.],
       [ 1.,  1.,  0., ...,  7.,  6.,  2.],
       [ 1.,  1.,  1., ..., 10.,  6.,  6.],
       ...,
       [ 0.,  0.,  1., ...,  3.,  5.,  3.],
       [ 0.,  0.,  1., ..., 11.,  6.,  8.],
       [ 1.,  1.,  1., ..., 11.,  5.,  6.]])

In [ ]:
# разбиваем датасет на матрицу параметров (X) и вектор целевой переменной (Y)
X, Y = dataset[:,1:22], dataset[:,0]

# создаем модели, добавляем слои один за другим
model = Sequential()
model.add(Dense(12, input_dim=21, activation='relu')) # входной слой требует задать input_dim
model.add(Dense(100, activation='relu'))
# model.add(Dense(8, activation='relu'))
#model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid')) # сигмоида вместо relu для определения вероятности

# компилируем модель, используем градиентный спуск adam
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=['accuracy'])

# обучаем нейронную сеть
model.fit(X, Y, epochs = 50, batch_size=10)

# оцениваем результат
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/50
7070/7070 [==============================] - 30s 4ms/step - loss: 0.5378 - accuracy: 0.7276
Epoch 2/50
7070/7070 [==============================] - 17s 2ms/step - loss: 0.5209 - accuracy: 0.7410
Epoch 3/50
7070/7070 [==============================] - 17s 2ms/step - loss: 0.5156 - accuracy: 0.7452
Epoch 4/50
7070/7070 [==============================] - 16s 2ms/step - loss: 0.5131 - accuracy: 0.7461
Epoch 5/50
7070/7070 [==============================] - 16s 2ms/step - loss: 0.5107 - accuracy: 0.7485
Epoch 6/50
7070/7070 [==============================] - 17s 2ms/step - loss: 0.5097 - accuracy: 0.7483
Epoch 7/50
7070/7070 [==============================] - 17s 2ms/step - loss: 0.5088 - accuracy: 0.7488
Epoch 8/50
7070/7070 [==============================] - 18s 3ms/step - loss: 0.5081 - accuracy: 0.7482
Epoch 9/50
7070/7070 [==============================] - 17s 2ms/step - loss: 0.5078 - accuracy: 0.7498
Epoch 10/50
7070/7070 [==============================] - 16s 2ms/step - l